version: "2.3"

services:

  app:
    image: airtonix/phaser-game-test
    build:
      dockerfile: ./Dockerfile
      context: ./app
      target: install
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: npm run dev
    volumes:
      - ./app:/home/dev
