version: "2.3"

services:

  app:
    image: docker.pkg.github.com/airtonix/phaser-tutorial-one/app:7fd22bfa0ce231f35efea67a5a84bf2e5f0885ce
    ports:
      - 3000:3000
      - 3030:3030
    environment:
      - PORT=3000
      - HMR_PORT=3030
      - CHOKIDAR_USEPOLLING=1
    command: tusk dev
    volumes:
      - ./app:/app
      - /app/node_modules
