version: "2.3"

services:

  app:
    image: docker.pkg.github.com/airtonix/phaser-tutorial-one/app:3f3a3e78b87ba34bb058b5683bd4b39e6d94eaf0
    ports:
      - 3000:3000
      - 3030:3030
    environment:
      - PORT=3000
      - HMR_PORT=3030
      - CHOKIDAR_USEPOLLING=1
    command: tusk dev
    volumes:
      - ./app:/app
      - /app/node_modules
