name: Docker Image CI

on: [push]
env:
  PATH: "$PATH:~/bin"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Tusk
      run: curl -sL https://git.io/tusk | sh -s -- -b ~/bin
    - name: build ci image
      run: tusk ci:setup
        
