name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: echo "::add-path::~/bin"
    - name: Install Tusk
      run: curl -sL https://git.io/tusk | sh -s -- -b ~/bin
    - name: build ci image
      run: tusk ci:setup
        
