name: PR Checks

on:
  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - develop

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  CI_SETTINGS__TUSK_VERSION: v0.5.1
  CI_SETTINGS__APP_DOCKER_REPO: docker.pkg.github.com/airtonix/phaser-tutorial-one

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Local bin path
        run: echo "::add-path::~/bin"

      - name: Install tusk
        run: >-
          curl -sL https://git.io/tusk | sh -s --
          -b ~/bin $CI_SETTINGS__TUSK_VERSION

      - name: Build ci image
        run: >-
          tusk docker:build
          --source=app
          --repo=$CI_SETTINGS__APP_DOCKER_REPO/app
          --tag=$GITHUB_SHA

      - name: Template docker-compose
        run: >-
          tusk docker:templates
          --version=$GITHUB_SHA

      - name: Run linting
        run: >-
          tusk ci:app:lint

      - name: Run tests
        run: >-
          tusk ci:app:test
